name       : glab
version    : 1.31.0
release    : 2
source     :
    - https://gitlab.com/gitlab-org/cli/-/archive/v1.31.0/cli-v1.31.0.tar.gz : 5648e88e7d6cc993227f5a4e80238af189bed09c7aed1eb12be7408e9a042747
license    : MIT
component  : system.utils
summary    : A GitLab CLI tool bringing GitLab to your command line
description: |
    GLab is an open source GitLab CLI tool bringing GitLab to your terminal next to where you are already working with git and your code without switching between windows and browser tabs. Work with issues, merge requests, watch running pipelines directly from your CLI among other features. Inspired by gh, the official GitHub CLI tool.
networking : yes
builddeps  :
    - golang
build      : |
    go build -o glab -ldflags "-s -w -X main.version=%version%" ./cmd/glab

    # manpages
    go run cmd/gen-docs/docs.go --manpage --path ./

    # command-line completions
    for s in bash fish zsh; do
    	./glab completion -s $s > $s.completions
    done
install    : |
    install -Dm00755 glab -t $installdir/usr/bin/
    install -Dm00644 glab.1 -t $installdir/usr/share/man/man1/

    install -Dm00644 bash.completions $installdir/usr/share/bash-completion/completions/glab
    install -Dm00644 fish.completions $installdir/usr/share/fish/vendor_completions.d/glab.fish
    install -Dm00644  zsh.completions $installdir/usr/share/zsh/site-functions/_glab
